import { JSDOM } from 'jsdom'
import { afterEach, describe, expect, it } from 'vitest'

import { startCodeImpact, type GeneratedMode, type ModeStore, type CodeImpactHandle } from './codeImpact'
import { mockDiffFile, mockFilesChangedPage, type MockDiffFile } from './mockGithubDiff'

const FILES: MockDiffFile[] = [
    { path: 'src/app.ts', additions: 12, deletions: 3, lines: ['+const a = 1', '-const a = 0', ' context'] },
    { path: 'src/app.test.ts', previousPath: 'src/old.test.ts', additions: 20, deletions: 0, lines: ["+import { it } from 'vitest'", "+const header = '// @generated by codegen'"] },
    { path: 'pnpm-lock.yaml', additions: 400, deletions: 90, lines: ['+lockfileVersion: 9'], comment: 'Why did this bump?' },
    { path: 'src/schema.ts', additions: 50, deletions: 5, lines: ['+// @generated by codegen', '+export type A = 1'] },
    { path: 'api/client.ts', additions: 70, deletions: 0, githubGenerated: true },
    { path: 'src/removed.py', additions: 0, deletions: 9, deleted: true, lines: ['-def gone(): pass'] },
]

class MemoryModeStore implements ModeStore {
    private listeners = new Set<(mode: GeneratedMode) => void>()
    constructor(public mode: GeneratedMode = 'show') {}
    async get() {
        return this.mode
    }
    async set(mode: GeneratedMode) {
        this.mode = mode
        this.listeners.forEach((listener) => listener(mode))
    }
    subscribe(listener: (mode: GeneratedMode) => void) {
        this.listeners.add(listener)
        return () => this.listeners.delete(listener)
    }
}

let handle: CodeImpactHandle | null = null
afterEach(() => handle?.stop())

function setup(files: MockDiffFile[] = FILES, expectedFiles?: number, store = new MemoryModeStore()) {
    const dom = new JSDOM('<!doctype html><html><body></body></html>', { pretendToBeVisual: true })
    const doc = dom.window.document
    doc.body.append(mockFilesChangedPage(doc, files, expectedFiles))
    handle = startCodeImpact(doc, store)
    return { doc, store, window: dom.window }
}

const frame = (window: Pick<Window, 'requestAnimationFrame'>) => new Promise((resolve) => window.requestAnimationFrame(resolve))
async function settle(window: Pick<Window, 'requestAnimationFrame'>) {
    await frame(window)
    await frame(window)
}

function overview(doc: Document): ShadowRoot {
    const host = doc.getElementById('posthog-code-impact')
    expect(host?.shadowRoot).toBeTruthy()
    return host!.shadowRoot!
}

function row(doc: Document, category: string): string {
    const cells = overview(doc).querySelectorAll(`[data-category="${category}"] > *`)
    return [...cells].map((cell) => cell.textContent).join(' ')
}

function badge(doc: Document, path: string): string {
    return doc.querySelector(`[data-tagsearch-path="${path}"] [data-vr-impact-badge]`)?.textContent ?? ''
}

describe('code impact on the Files changed page', () => {
    it('shows additions and deletions per category in the overview', async () => {
        const { doc, window } = setup()
        await settle(window)
        expect(row(doc, 'production')).toBe('Production 2 files +12 −12')
        expect(row(doc, 'test')).toBe('Test 1 file +20 −0')
        expect(row(doc, 'generated')).toBe('Generated 3 files +520 −95')
        expect(overview(doc).textContent).toContain('All 6 changed files are counted.')
    })

    it('keeps a test that quotes a generated marker as a test', async () => {
        const { doc, window } = setup()
        await settle(window)
        expect(badge(doc, 'src/app.test.ts')).toBe('Test')
    })

    it('checks generated headers only when the diff shows the start of the file', async () => {
        const { doc, window } = setup([
            { path: 'src/late.ts', additions: 1, deletions: 0, startLine: 40, lines: ['+// @generated by codegen'] },
            { path: 'src/early.ts', additions: 2, deletions: 0, lines: ['+// @generated by codegen', '+export const a = 1'] },
            { path: 'src/gone.ts', additions: 0, deletions: 2, deleted: true, lines: ['-// Code generated by sqlc. DO NOT EDIT.', '-export {}'] },
        ])
        await settle(window)
        expect(badge(doc, 'src/late.ts')).toBe('Production')
        expect(badge(doc, 'src/early.ts')).toBe('Generated')
        expect(badge(doc, 'src/gone.ts')).toBe('Generated')
        expect(overview(doc).textContent).toContain('1 file does not show its first lines')
    })

    it('marks every file header with its category and the reason', async () => {
        const { doc, window } = setup()
        await settle(window)
        expect(badge(doc, 'src/app.ts')).toBe('Production')
        expect(badge(doc, 'src/app.test.ts')).toBe('Test')
        expect(badge(doc, 'pnpm-lock.yaml')).toBe('Generated')
        const generated = doc.querySelector('[data-tagsearch-path="api/client.ts"] [data-vr-impact-badge]')
        expect(generated?.getAttribute('title')).toBe('Generated: GitHub marks this file as generated')
        expect(doc.querySelector('[data-tagsearch-path="src/app.test.ts"]')?.getAttribute('data-vr-impact')).toBe('test')
    })

    it('dims or hides generated lines from the overview controls and keeps comments visible', async () => {
        const { doc, store, window } = setup()
        await settle(window)
        const hide = overview(doc).querySelector<HTMLInputElement>('input[value="hide"]')!
        hide.click()
        await settle(window)
        expect(store.mode).toBe('hide')
        expect(doc.documentElement.getAttribute('data-vr-generated')).toBe('hide')
        expect(badge(doc, 'pnpm-lock.yaml')).toBe('Generated · hidden')
        expect(doc.querySelector('.review-comment')?.textContent).toBe('Why did this bump?')
    })

    it('follows a mode chosen in another tab', async () => {
        const { doc, store, window } = setup()
        await settle(window)
        await store.set('dim')
        await settle(window)
        expect(doc.documentElement.getAttribute('data-vr-generated')).toBe('dim')
        expect(overview(doc).querySelector<HTMLInputElement>('input[value="dim"]')?.checked).toBe(true)
    })

    it('says which counts are incomplete instead of counting unknown lines as production', async () => {
        const { doc, window } = setup(
            [
                { path: 'src/big.ts', additions: 3000, deletions: 10, collapsed: true },
                { path: 'assets/logo.png' },
            ],
            5,
        )
        await settle(window)
        const text = overview(doc).textContent ?? ''
        expect(text).toContain('3 files are not loaded yet')
        expect(text).toContain('1 file has no line counts')
        expect(text).toContain('1 file does not show its first lines, so its generated header was not checked')
        expect(row(doc, 'production')).toBe('Production 2 files +3000 −10')
    })

    it('picks up files GitHub loads later without rescanning for its own changes', async () => {
        const { doc, window } = setup(FILES.slice(0, 1), 2)
        await settle(window)
        expect(overview(doc).textContent).toContain('1 file is not loaded yet')
        doc.querySelector('.js-diff-progressive-container')!.append(mockDiffFile(doc, { path: 'tests/test_api.py', additions: 4, deletions: 1, lines: ['+def test_api(): pass'] }))
        await settle(window)
        expect(row(doc, 'test')).toBe('Test 1 file +4 −1')
        expect(badge(doc, 'tests/test_api.py')).toBe('Test')
        const before = handle!.scans
        await settle(window)
        await settle(window)
        expect(handle!.scans).toBe(before)
    })

    it('removes its overview, badges, and styles when stopped', async () => {
        const { doc, window } = setup()
        await settle(window)
        handle!.stop()
        handle = null
        expect(doc.getElementById('posthog-code-impact')).toBeNull()
        expect(doc.getElementById('posthog-code-impact-style')).toBeNull()
        expect(doc.querySelector('[data-vr-impact-badge]')).toBeNull()
        expect(doc.querySelector('[data-vr-impact]')).toBeNull()
        expect(doc.documentElement.hasAttribute('data-vr-generated')).toBe(false)
    })

    it('stays out of the way when the page has no diff it understands', async () => {
        const { doc, window } = setup([], 0)
        await settle(window)
        expect(doc.getElementById('posthog-code-impact')?.hidden ?? true).toBe(true)
    })
})
