import { describe, expect, it } from 'vitest'

import { classifyFile, summarizeImpact, type DiffFileFacts } from './codeImpact'

function facts(overrides: Partial<DiffFileFacts>): DiffFileFacts {
    return { path: 'src/app.ts', additions: 1, deletions: 0, githubGenerated: false, fileHeader: [], ...overrides }
}

describe('classifyFile', () => {
    it.each([
        ['src/app.ts'],
        ['frontend/src/scenes/Dashboard.tsx'],
        ['posthog/api/insight.py'],
        ['docs/testing.md'],
        ['src/contest.ts'],
    ])('treats %s as production', (path) => {
        expect(classifyFile(facts({ path })).category).toBe('production')
    })

    it.each([
        ['src/app.test.ts'],
        ['src/Button.spec.tsx'],
        ['src/__tests__/render.tsx'],
        ['src/__snapshots__/Button.test.tsx.snap'],
        ['posthog/api/test/test_insight.py'],
        ['tests/conftest.py'],
        ['posthog/models/insight_test.py'],
        ['e2e/login.spec.js'],
    ])('treats %s as a test', (path) => {
        expect(classifyFile(facts({ path }))).toMatchObject({ category: 'test', reason: expect.stringMatching(/test/i) })
    })

    it.each([
        ['pnpm-lock.yaml'],
        ['frontend/package-lock.json'],
        ['poetry.lock'],
        ['uv.lock'],
        ['go.sum'],
        ['dist/vendor.min.js'],
        ['api/v1/service.pb.go'],
        ['proto/service_pb2.py'],
        ['src/__generated__/schema.ts'],
        ['src/queries.generated.ts'],
    ])('treats the standard artifact %s as generated', (path) => {
        expect(classifyFile(facts({ path }))).toMatchObject({ category: 'generated', reason: expect.stringMatching(/standard generated file/) })
    })

    it('trusts GitHub marking a file as generated over its path', () => {
        expect(classifyFile(facts({ path: 'src/app.test.ts', githubGenerated: true }))).toMatchObject({
            category: 'generated',
            reason: expect.stringMatching(/GitHub/),
        })
    })

    it.each([
        ['// @generated by codegen'],
        ['# Code generated by protoc-gen-go. DO NOT EDIT.'],
        ['/* This file was automatically generated. */'],
        [' * @generated SignedSource<<abc>>'],
        ['<!-- Auto-generated by docs-gen -->'],
    ])('recognizes the header marker "%s"', (line) => {
        expect(classifyFile(facts({ fileHeader: ['/**', line, 'import x'] }))).toMatchObject({
            category: 'generated',
            reason: expect.stringMatching(/header/),
        })
    })

    it.each([
        ['src/codegen.test.ts', 'test', ["import { it } from 'vitest'", "const header = '// @generated by codegen'"]],
        ['src/codegen.ts', 'production', ['export function banner() {', "    return '# Code generated. DO NOT EDIT.'"]],
        ['src/notes.ts', 'production', ['export const a = 1', '// @generated files are skipped by the linter']],
        ['src/readme.py', 'production', ['"""Explains why we never ship automatically generated code."""']],
    ])('ignores generated wording in the literals of %s', (path, category, fileHeader) => {
        expect(classifyFile(facts({ path, fileHeader })).category).toBe(category)
    })
    it('says when the header could not be checked because the diff does not show the start of the file', () => {
        expect(classifyFile(facts({ fileHeader: null }))).toMatchObject({ category: 'production', markersChecked: false })
    })

    it('classifies a rename by its new path', () => {
        expect(classifyFile(facts({ path: 'src/app.test.ts', previousPath: 'src/app.ts' })).category).toBe('test')
    })
})

describe('summarizeImpact', () => {
    it('adds additions and deletions per category', () => {
        const summary = summarizeImpact(
            [
                classifyFile(facts({ path: 'src/a.ts', additions: 10, deletions: 2 })),
                classifyFile(facts({ path: 'src/b.ts', additions: 1, deletions: 4 })),
                classifyFile(facts({ path: 'src/a.test.ts', additions: 30, deletions: 0 })),
                classifyFile(facts({ path: 'pnpm-lock.yaml', additions: 900, deletions: 120 })),
            ],
            4,
        )
        expect(summary.totals).toEqual({
            production: { files: 2, additions: 11, deletions: 6 },
            test: { files: 1, additions: 30, deletions: 0 },
            generated: { files: 1, additions: 900, deletions: 120 },
        })
        expect(summary.complete).toBe(true)
    })

    it('reports files whose counts or markers are unknown instead of hiding them', () => {
        const summary = summarizeImpact(
            [
                classifyFile(facts({ path: 'src/a.ts', additions: null, deletions: null })),
                classifyFile(facts({ path: 'src/b.ts', fileHeader: null })),
            ],
            2,
        )
        expect(summary).toMatchObject({ uncountedFiles: 1, uncheckedFiles: 1, notLoadedFiles: 0, complete: false })
        expect(summary.totals.production.files).toBe(2)
    })

    it('reports files GitHub has not loaded on the page yet', () => {
        const summary = summarizeImpact([classifyFile(facts({}))], 5)
        expect(summary).toMatchObject({ notLoadedFiles: 4, complete: false })
    })

    it('stays incomplete when the total file count is unknown', () => {
        expect(summarizeImpact([classifyFile(facts({}))], null)).toMatchObject({ notLoadedFiles: null, complete: false })
    })
})
